export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import { ToastContainer } from "react-toastify";
import "../globals.css";


export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ direction: "rtl" }}>
      <body>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        {children}
      </body>
    </html>
  );
}
