export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import "../globals.css";

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ direction: "rtl" }}>
      <body>{children}</body>
    </html>
  );
}
